//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bfeEntities2 : DbContext
    {
        public bfeEntities2()
            : base("name=bfeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Кисломолочные_продукты> Кисломолочные_продукты { get; set; }
        public virtual DbSet<Масло> Масло { get; set; }
        public virtual DbSet<Молоко_и_сливки> Молоко_и_сливки { get; set; }
        public virtual DbSet<Молочные_консервы> Молочные_консервы { get; set; }
        public virtual DbSet<Сухие_молочные_продукты> Сухие_молочные_продукты { get; set; }
        public virtual DbSet<Сыры> Сыры { get; set; }
    }
}
