//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Молоко_и_сливки
    {
        public int id { get; set; }
        public string Дата { get; set; }
        public string Молоко_обезжиренное { get; set; }
        public string Молоко_2_5 { get; set; }
        public string Молоко_3_2 { get; set; }
        public string Сливки_10 { get; set; }
        public string Сливки_20 { get; set; }
    
        public virtual Кисломолочные_продукты Кисломолочные_продукты { get; set; }
        public virtual Масло Масло { get; set; }
        public virtual Молочные_консервы Молочные_консервы { get; set; }
        public virtual Сухие_молочные_продукты Сухие_молочные_продукты { get; set; }
        public virtual Сыры Сыры { get; set; }
    }
}
